name: newappchat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/backHomeApp.png
    - assets/imgfigma.png
    - assets/logo.png
    - assets/peito.png
    - assets/costas.jpg
    - assets/cardio.jpg
    - assets/perna.jpg
    - assets/background.jpg
    - assets/fundo.png
